
media:
  input: content/media
  output: /media

content:
  - name: blog
    label: Blog Posts
    type: collection
    path: content/blog
    filename: "{year}-{month}-{day}-{primary}.md"
    view:
      fields: [title, date, description]
      primary: title
      sort: [date, title]
      default:
        sort: date
        order: desc
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: text
        required: true
      - name: date
        label: Publication Date
        type: date
        required: true
      - name: slug
        label: URL Slug
        type: string
        required: true
        pattern: 
          regex: '^[a-z0-9-]+$'
          message: 'Must contain only lowercase letters, numbers, and hyphens'
      - name: content
        label: Content
        type: rich-text
        required: true

