
collections:
  - name: blog
    label: Blog Posts
    folder: content/blog
    create: true
    fields:
      - name: title
        label: Title
        widget: string
        required: true
      - name: description
        label: Description
        widget: text
        required: true
      - name: date
        label: Publication Date
        widget: datetime
        required: true
      - name: slug
        label: URL Slug
        widget: string
        required: true
        pattern: ['^[a-z0-9-]+$', 'Must contain only lowercase letters, numbers, and hyphens']
      - name: content
        label: Content
        widget: markdown
        required: true
